# This is a sample build configuration for C++ � Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: 
  name: graalunige/devel-testbench
  username: $DOCKER_HUB_USERNAME_WANDERFRA
  password: $DOCKER_HUB_PASSWORD_WANDERFRA
  email: $DOCKER_HUB_EMAIL_WANDERFRA

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - sudo apt install -y libgeographic-dev
          - sudo apt install -y libconfig++-dev
          - mkdir dependencies
          - cd dependencies
          - git clone git@bitbucket.org:isme_robotics/rml.git 
          - cd rml
          - cmake .
          - make install
          #- cd ..
          #- git clone git@bitbucket.org:isme_robotics/ctrl_toolbox.git
          #- cd ctrl_toolbox          
          #- cmake .
          #- make install
          - cd ../..
          - cmake .
          - make 
